import * as fs from 'node:fs';
import * as path from 'node:path';

const KEY_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

export function parseEnvExample(filePath: string): string[] {
  if (!fs.existsSync(filePath)) return [];
  const keys: string[] = [];
  for (const raw of fs.readFileSync(filePath, 'utf8').split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    if (KEY_RE.test(key) && !keys.includes(key)) keys.push(key);
  }
  return keys;
}

function needsQuoting(v: string): boolean {
  if (v === '') return true;
  if (/[\s#"'\\]/.test(v)) return true;
  if (/^\s/.test(v) || /\s$/.test(v)) return true;
  if (v.includes('\n') || v.includes('\r')) return true;
  return false;
}

function escape(v: string): string {
  return v.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\t/g, '\\t');
}

export function formatValue(v: string): string {
  return needsQuoting(v) ? `"${escape(v)}"` : v;
}

export function renderEnv(
  ordered: string[],
  values: Record<string, string>,
  opts: { project?: string; environment?: string } = {}
): string {
  const lines = [
    `# Generated by envpact-vscode on ${new Date().toISOString()}`,
    '# DO NOT COMMIT — add .env to .gitignore',
  ];
  if (opts.environment) lines.push(`# environment: ${opts.environment}`);
  if (opts.project) lines.push(`# project: ${opts.project}`);
  lines.push('');
  for (const k of ordered) {
    if (k in values) lines.push(`${k}=${formatValue(values[k])}`);
  }
  return lines.join('\n') + '\n';
}

export function writeEnvAtomic(filePath: string, content: string): void {
  const dir = path.dirname(path.resolve(filePath));
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const tmp = `${filePath}.tmp.${process.pid}.${Date.now()}`;
  fs.writeFileSync(tmp, content, { encoding: 'utf8', mode: 0o600 });
  fs.renameSync(tmp, filePath);
}

export function ensureGitignoreCovers(cwd: string, pattern: string): boolean {
  const file = path.join(cwd, '.gitignore');
  let existing = '';
  try { existing = fs.readFileSync(file, 'utf8'); } catch (_e) { /* new file */ }
  if (existing.split(/\r?\n/).some(l => l.trim() === pattern)) return false;
  const next = (existing && !existing.endsWith('\n') ? existing + '\n' : existing) + pattern + '\n';
  fs.writeFileSync(file, next);
  return true;
}
