/**
 * envpact-vscode global-env — generate ~/.envpact/.env from
 * ~/.envpact/.env.example.global per SHARED_SPEC §1.6 / §5.1.
 *
 * Mirrors the rules every other envpact component follows so the
 * three writers (cli, mcp, vscode) produce byte-identical output for
 * the same vault state:
 *
 *   - On first run, if the global example template is absent, create
 *     it by listing every shared key in alphabetical order, no
 *     comments, KEY= (no value hint).
 *   - For each line of the template:
 *       * blank or `# comment` → copy verbatim
 *       * `KEY=` or `KEY=hint`:
 *           - shared.KEY missing       → `# KEY: not in vault`
 *           - shared.KEY enc:*         → `# KEY: encrypted — decrypt-via-cli`
 *           - shared.KEY plain         → `KEY=<formatted value>`
 *   - Header is "# Generated by envpact (global) on <ISO>\n# DO NOT
 *     COMMIT — managed by envpact\n".
 *   - File mode 0600 (best-effort on Windows).
 *   - Atomic write (.tmp + rename).
 *   - NEVER auto-pushes back to the vault — read-only mirror.
 *
 * Returns counts the caller can surface to the user; values never
 * leave this module on disk except via the generated mirror file.
 */

import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

import type { Vault, VaultEntry } from './resolver';
import { ENC_PREFIX } from './resolver';
import { formatValue } from './envwriter';

const HOME = process.env.USERPROFILE || process.env.HOME || os.homedir();
export const GLOBAL_DIR = path.join(HOME, '.envpact');
export const GLOBAL_ENV_FILE = path.join(GLOBAL_DIR, '.env');
export const GLOBAL_EXAMPLE_FILE = path.join(GLOBAL_DIR, '.env.example.global');

export interface GenerateGlobalEnvResult {
  /** Absolute path of the written file (always GLOBAL_ENV_FILE). */
  outputPath: string;
  /** Path of the example template (always GLOBAL_EXAMPLE_FILE). */
  examplePath: string;
  /** Number of KEYs that resolved to a plaintext value. */
  resolvedCount: number;
  /** Number of KEYs that were encrypted (commented out, not written). */
  encrypted: number;
  /** Number of KEYs in the example but absent from vault.shared. */
  notInVault: number;
  /** True if we just auto-created .env.example.global on this run. */
  generatedGlobalExample: boolean;
}

const KEY_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

/**
 * Auto-generate the default `.env.example.global` if absent. Lists
 * every shared key in alphabetical order with no comments and no
 * value hints — `KEY=`.
 */
export function ensureGlobalExampleExists(vault: Vault): boolean {
  if (!fs.existsSync(GLOBAL_DIR)) {
    fs.mkdirSync(GLOBAL_DIR, { recursive: true });
  }
  if (fs.existsSync(GLOBAL_EXAMPLE_FILE)) return false;
  const sharedKeys = Object.keys(vault.shared || {}).sort();
  const body = sharedKeys.length
    ? sharedKeys.map((k) => `${k}=`).join('\n') + '\n'
    : '';
  // Atomic write so a half-written template never wins a race.
  const tmp = `${GLOBAL_EXAMPLE_FILE}.tmp.${process.pid}.${Date.now()}`;
  fs.writeFileSync(tmp, body, { encoding: 'utf8', mode: 0o600 });
  fs.renameSync(tmp, GLOBAL_EXAMPLE_FILE);
  return true;
}

/**
 * Pure body renderer — given the example template content and the
 * vault, produce the body of the global .env (no header). Walks the
 * template line by line preserving line endings (CRLF or LF).
 */
export function renderGlobalEnvBody(
  exampleContent: string,
  vault: Vault,
): { body: string; resolvedCount: number; encrypted: number; notInVault: number } {
  const shared: Record<string, VaultEntry> = vault.shared || {};
  let resolvedCount = 0;
  let encrypted = 0;
  let notInVault = 0;

  // Walk character-by-character to preserve trailing newlines and CRLF.
  const out: string[] = [];
  let start = 0;
  const segments: { text: string; ending: string }[] = [];
  for (let i = 0; i < exampleContent.length; i++) {
    if (exampleContent[i] === '\n') {
      let end = i;
      let ending = '\n';
      if (end > 0 && exampleContent[end - 1] === '\r') {
        end = i - 1;
        ending = '\r\n';
      }
      segments.push({ text: exampleContent.slice(start, end), ending });
      start = i + 1;
    }
  }
  const tail = start < exampleContent.length ? exampleContent.slice(start) : null;

  const transform = (line: string): string => {
    const trimmed = line.trim();
    if (trimmed === '' || trimmed.startsWith('#')) return line;
    const eq = line.indexOf('=');
    if (eq < 0) return line;
    const lhs = line.slice(0, eq);
    const key = lhs.trim();
    if (!KEY_RE.test(key)) return line;
    const leading = lhs.slice(0, lhs.length - lhs.trimStart().length);

    const entry = shared[key];
    if (!entry || typeof entry.value !== 'string') {
      notInVault += 1;
      return `${leading}# ${key}: not in vault`;
    }
    if (entry.value.startsWith(ENC_PREFIX)) {
      encrypted += 1;
      return `${leading}# ${key}: encrypted — decrypt-via-cli`;
    }
    resolvedCount += 1;
    return `${leading}${key}=${formatValue(entry.value)}`;
  };

  for (const { text, ending } of segments) {
    out.push(transform(text));
    out.push(ending);
  }
  if (tail !== null) {
    out.push(transform(tail));
  }

  return { body: out.join(''), resolvedCount, encrypted, notInVault };
}

/**
 * Atomic write of the global .env. Mode 0600 — best-effort on Windows
 * (the OS may downgrade it but we still try).
 */
function atomicWrite(filePath: string, content: string): void {
  const dir = path.dirname(path.resolve(filePath));
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const tmp = `${filePath}.tmp.${process.pid}.${Date.now()}`;
  fs.writeFileSync(tmp, content, { encoding: 'utf8', mode: 0o600 });
  fs.renameSync(tmp, filePath);
}

/**
 * Generate ~/.envpact/.env from ~/.envpact/.env.example.global. Side
 * effect: writes both files atomically when they need to change.
 *
 * Caller responsibility: provide a freshly-loaded `vault`. This module
 * never decrypts secrets; encrypted entries become commented-out
 * placeholder lines. Values never enter the model context: callers
 * surface the returned counts only.
 */
export function generateGlobalEnv(vault: Vault): GenerateGlobalEnvResult {
  const generatedGlobalExample = ensureGlobalExampleExists(vault);
  const exampleContent = fs.readFileSync(GLOBAL_EXAMPLE_FILE, 'utf8');
  const ts = new Date().toISOString();
  const header =
    `# Generated by envpact (global) on ${ts}\n` +
    `# DO NOT COMMIT — managed by envpact\n`;
  const { body, resolvedCount, encrypted, notInVault } = renderGlobalEnvBody(
    exampleContent,
    vault,
  );
  atomicWrite(GLOBAL_ENV_FILE, header + body);
  return {
    outputPath: GLOBAL_ENV_FILE,
    examplePath: GLOBAL_EXAMPLE_FILE,
    resolvedCount,
    encrypted,
    notInVault,
    generatedGlobalExample,
  };
}
